### ISSUE TITLE
Source code/MacOS version

### ISSUE THREAD

**Issue by wildberry93** [yuedongyang/DLIGAND2#1]
Hi!

Is it possible to provide the source code for the program? I want to compile and use it on MacOS.

Thank you!

**Comment by pincher-chen** [comment]
Can you leave a email? I can give you the source code.

**Comment by wildberry93** [comment]
Hi! Thank you! My email is jagoda.jablonska@weizmann.ac.il

**Comment by brianjimenez** [comment]
Sorry for commenting in a closed issue, but I'm also interested in compiling and testing it in macOS.
